%% File that does all the figures in the paper

clc 
clear all
close all
% --- paths (robust to current working directory) ---
script_dir  = fileparts(mfilename('fullpath'));
addpath(genpath(fullfile(script_dir, 'Subroutines')));
results_dir = fullfile(script_dir, 'SimulationsResults');
addpath(results_dir);

%% some basic savings properties

save_picture = 1;
close_picture = 0;

%% Figure 1 

method_pair_fields = {
    {'LP.Studentized.method7', 'LP.Studentized.method2'},
    {'SLP.Studentized.method7', 'SLP.Studentized.method2'},
    {'VAR.Studentized.method7', 'VAR.Studentized.method2'},
    {'TLP.Studentized.method7', 'TLP.Studentized.method2'}
};

plot_coverage_comparison_vertical_dual(method_pair_fields, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T200_sim1000_pL10_pV1_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV1_eta1_DGP_OleaSW_P1.mat'}, ...
    [1 2], save_picture, close_picture, 'coverage');

%% Figure 2

plot_var_tlp_method_coverage_dual( ...
    {'Final16June_T200_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat'}, ...
    8,'coverage' ,save_picture, close_picture);

%% Figure 3

metric = 'length';  % e.g. 'length' or 'coverage'
estimators = {'VAR', 'TLP'};  % e.g. {'LP'} or {'LP', 'SLP', 'VAR', 'TLP'}

plot_var_tlp_method_metric_2x2( ...
    {'Final16June_T200_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat'}, ...
    8, metric, estimators, save_picture, close_picture);

%% Figure 4

plot_weights_coverage_by_eta_2x2( ...
    [200, 800], ...
    [1, 2, 4, 8, 16, 32, 64], ...
    {'1', '2', '4', '8', '16', '32', '64'}, ...
    'Final16June_T%d_sim1000_pL10_pV8_eta%s_DGP_OleaSW_P1.mat', ...
    8, [], save_picture, close_picture);

%% Figure 5-7, C1 - C3 

p_picture = [1];
plot_markers = 0;
legend_names = {{"Targeted Local Projection","Local Projection","Vector Autoregression",...
    "Bayesian Local Projection","Smooth Local Projection"},1};
stat_of_interest = {'coverage', 'length','bias', 'std','rmse'};
other_methods = {'LP.Studentized.method7', 'VAR.Studentized.method7','BLP', 'SLP.Studentized.method7'};

%eta = 1
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB1', close_picture, plot_markers, legend_names);

%eta = 2
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta2_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta2_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB2', close_picture, plot_markers, legend_names);

%eta = 4
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta4_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta4_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB4', close_picture, plot_markers, legend_names);

%eta = 8
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta8_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta8_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB8', close_picture, plot_markers, legend_names);

%eta = 16
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta16_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta16_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB16', close_picture, plot_markers, legend_names);

%eta = 32
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta32_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta32_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB32', close_picture, plot_markers, legend_names);

%eta = 64
plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16June_T200_sim1000_pL10_pV8_eta64_DGP_OleaSW_P1.mat', ...
     'Final16June_T800_sim1000_pL10_pV8_eta64_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'BB64', close_picture, plot_markers, legend_names);


%% Figures 8, D1 + tables 1,2

plot_BLP_application_4x2( ...
    'BLP_application_T259_pL10_pV4_FFRshock.mat', ...
    save_picture, close_picture);

plot_BLP_application_4x2( ...
    'BLP_application_T259_pL8_pV4_FFRshock.mat', ...
    save_picture, close_picture);

blp_table_vars = {'RGDP_to_FFR', 'RCON_to_FFR', 'RINV_to_FFR', 'HOURS_to_FFR'};
blp_table_horizons = 16;

BLP_table_pL10_pV4 = BLP_application_significance_table( ...
    'BLP_application_T259_pL10_pV4_FFRshock.mat', ...
    blp_table_vars, blp_table_horizons, ...
    'TablesAndPlots', 'IRF_Significance_Table_BLP_pL10_pV4.tex');

BLP_table_pL8_pV4 = BLP_application_significance_table( ...
    'BLP_application_T259_pL8_pV4_FFRshock.mat', ...
    blp_table_vars, blp_table_horizons, ...
    'TablesAndPlots', 'IRF_Significance_Table_BLP_pL8_pV4.tex');

%% Figure C4-C6

plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16JuneGarch_T200_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat', ...
     'Final16JuneGarch_T800_sim1000_pL10_pV8_eta1_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'Garch1', close_picture, plot_markers, legend_names);

plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16JuneGarch_T200_sim1000_pL10_pV8_eta2_DGP_OleaSW_P1.mat', ...
     'Final16JuneGarch_T800_sim1000_pL10_pV8_eta2_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'Garch2', close_picture, plot_markers, legend_names);

plot_stat_by_horizon_dual(stat_of_interest, ...
    {'Final16JuneGarch_T200_sim1000_pL10_pV8_eta4_DGP_OleaSW_P1.mat', ...
     'Final16JuneGarch_T800_sim1000_pL10_pV8_eta4_DGP_OleaSW_P1.mat'}, ...
    'TLP.Studentized.method7',other_methods, ...
    p_picture, 'Garch4', close_picture, plot_markers, legend_names);
